### ISSUE TITLE
Password doesn't change

### ISSUE THREAD

**Issue by bazzadazza72** [Billy4896/QR-Code-Generator#2]
My password doesn't change. XD

**Comment by Billy4896** [comment]
Bug squashed, working as intended now. I was using the newly created hashed password as the identifier to find the desired dictionary when I needed to be using the username obviously. Must of been a late night haha. Fixed the sha issue too, apparently I was shaing in that function with 512 instead of 215 causing issues when resetting the password *facepalm*.
